Make seqeval wrapper resistant
CLARIN-PL/embeddings pull request #115
Opened 2021-11-18 13:30 UTC by albert097

There is an oversight in the original seqeval code, that does not protect from passing a wrong combination of arguments. This pull request is a patch for it.

2021-12-07 15:01 UTC, laugustyniak commented on examples/evaluate_sequence_labelling.py
> +class TaggingScheme(str, Enum):
why not use enums' list in `tagging_scheme` and other variables?

2021-12-07 19:31 UTC, ktagowski requested changes

2021-12-07 19:31 UTC, ktagowski commented on examples/evaluate_sequence_labelling.py
> +class TaggingScheme(str, Enum):
I agree with @laugustyniak. I would use Enums in other places.

2021-12-20 18:39 UTC, ktagowski approved these changes

2021-12-21 09:45 UTC, merged